name: khb_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  get: ^4.6.6

  # Keyboard Dismisser
  keyboard_dismisser: ^3.0.0

  # Code Generation and Data Classes
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  # Screen Util
  flutter_screenutil: ^5.9.3

  # Network Connection Checker
  connectivity_plus: ^6.0.5

  # HTTP Requests
  http: ^1.2.2

  # JSON Serialization
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  timeline_tile: ^2.0.0

  # Logging
  logger: ^2.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Loading Indicator
  flutter_easyloading: ^3.0.5

  # Device Info
  device_info_plus: ^11.0.0

  # Permissions Handling
  permission_handler: ^11.3.1

  # SVG Handling
  flutter_svg: ^2.0.10+1
  # Carousel Slider
  carousel_slider: ^5.0.0

  # Shimmer Effect
  shimmer: ^3.0.0

  bottom_picker: ^2.4.0

  # Firebase Core
  firebase_core: ^3.8.0
  dropdown_search: ^5.0.6

  # Firebase Messaging (Push Notifications)
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  #  firebase_in_app_messaging: ^0.8.0+10
  #  firebase_app_installations: ^0.3.1+6

  # PageView List Grid
  infinite_scroll_pagination: ^4.0.0

  # Internationalization
  intl: ^0.19.0
  async: ^2.11.0

  # Bottom Navigation Bar
  animated_bottom_navigation_bar: ^1.3.3

  # Image Compression
  flutter_image_compress: ^2.3.0
  # Animations and Gradients
  animate_do: ^3.3.4
  animate_gradient: ^0.0.3
  # Photo Viewer
  photo_view: ^0.15.0
  image: ^4.3.0
  # Onboarding Slider
  smooth_page_indicator: 1.2.0+3

  # Bottom Sheet
  modal_bottom_sheet: ^3.0.0

  # Toast Notifications
  toastification: ^2.3.0

  # Cached Network Image
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  uuid: ^4.5.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_gen_runner: ^5.2.0
  flutter_flavorizr: ^2.2.3

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/gif/
  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/font/SFUIText/SFUIText-Bold.otf
        - asset: assets/font/SFUIText/SFUIText-BoldG1.otf
        - asset: assets/font/SFUIText/SFUIText-BoldG2.otf
        - asset: assets/font/SFUIText/SFUIText-BoldG3.otf
        - asset: assets/font/SFUIText/SFUIText-Heavy.otf
        - asset: assets/font/SFUIText/SFUIText-Light.otf
        - asset: assets/font/SFUIText/SFUIText-Medium.otf
        - asset: assets/font/SFUIText/SFUIText-Regular.otf
        - asset: assets/font/SFUIText/SFUIText-RegularG1.otf
        - asset: assets/font/SFUIText/SFUIText-RegularG2.otf
        - asset: assets/font/SFUIText/SFUIText-RegularG3.otf
        - asset: assets/font/SFUIText/SFUIText-Semibold.otf
    - family: Hanuman
      fonts:
        - asset: assets/font/Hanuman/Hanuman-Black.ttf
        - asset: assets/font/Hanuman/Hanuman-Bold.ttf
        - asset: assets/font/Hanuman/Hanuman-Light.ttf
        - asset: assets/font/Hanuman/Hanuman-Regular.ttf
        - asset: assets/font/Hanuman/Hanuman-Thin.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
